### ISSUE TITLE
non-vectored interrupts?

### ISSUE THREAD

**Issue by andres-erbsen** [mit-plv/riscv-coq#3]
https://content.riscv.org/wp-content/uploads/2017/05/riscv-privileged-v1.10.pdf 3.1.12:

> The encoding of the MODE field is shown in Table 3.5. When MODE=Direct, all traps into
> machine mode cause the pc to be set to the address in the BASE field. When MODE=Vectored,
> all synchronous exceptions into machine mode cause the pc to be set to the address in the BASE
> field, whereas interrupts cause the pc to be set to the address in the BASE field plus four times
> the interrupt cause number. For example, a machine-mode timer interrupt (see Table 3.6) causes
> the pc to be set to BASE+0x1c. Setting MODE=Vectored may impose an additional alignment
> constraint on BASE, requiring up to 4 × XLEN-byte alignment.

https://github.com/mit-plv/riscv-coq/blob/2b6e113b0aeb9f8498e2739829c39c11e49483c5/src/Program.v#L62 seems to assume `MODE=Vectored`.

**Comment by andres-erbsen** [comment]
@samuelgruetter does this belong here or in riscv-spec?

**Comment by samuelgruetter** [comment]
I'll eventually just translate the riscv-semantics haskell code to Coq, so you'd have to check if

https://github.com/mit-plv/riscv-semantics/blob/c4687e05ac7f14590f18dc4d5aac3c2f20519183/src/Spec/Machine.hs#L129-L164

does what you want.
